services:
  censorlab:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: censorlab:latest
    ports:
      - "1116:1116"
    stdin_open: true
    tty: true

  censorlab-nfq:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: censorlab:latest
    ports:
      - "1116:1116"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    stdin_open: true
    tty: true
